name: TiaAndMichael
favicon: null
layout_spectrum: 0.15723037254065275
typography_spectrum: 0.8778151758015156
title: Wedding of Tia and Michael
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafffa'
    - '#5fa1fe'
    - '#040700'
    - '#6f605b'
    - '#b7c285'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
