name: TiaAndMichael
favicon: null
layout_spectrum: 0.15723037254065275
typography_spectrum: 0.8778151758015156
title: Wedding of Tia and Michael
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000100'
    - '#f1f3f2'
    - '#3f61a1'
    - '#8fa6cf'
    - '#985230'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
